/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_gm.RecibosHonorarios;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jeanv
 */
public class frmRecibosHonorarios extends javax.swing.JInternalFrame {

    boolean esNuevo = false;

    /**
     * Creates new form frmRecibosHonorarios
     */
    public frmRecibosHonorarios() {
        initComponents();
        // Personalizar header
        JTableHeader header = tblHonorarios.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(JLabel.CENTER);
                setBackground(Color.DARK_GRAY);
                setForeground(Color.WHITE);
                setFont(getFont().deriveFont(Font.BOLD, 13));
                return this;
            }
        });

        DefaultTableModel modelo = (DefaultTableModel) tblHonorarios.getModel();
        // Ocultamos las columnas "Id" y "Direccion"
        OcultarColumna(tblHonorarios, 6);
        OcultarColumna(tblHonorarios, 0);

        DatosRecibosHonorarios.Listar(modelo);
        DatosRecibosHonorarios.Habilitar(escritorio, false);

        // Dejamos los combo boxes sin seleccion
        cboDistrito.setSelectedIndex(-1);
        cboPago.setSelectedIndex(-1);

        // Quitar la edicion de las celdas
        tblHonorarios.setCellSelectionEnabled(false);
        // Poder seleccionar fila(s) de la tabla
        tblHonorarios.setRowSelectionAllowed(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        txtIR = new javax.swing.JTextField();
        txtConcepto = new javax.swing.JTextField();
        cboPago = new javax.swing.JComboBox<>();
        cboDistrito = new javax.swing.JComboBox<>();
        txtImpNeto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtImpTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHonorarios = new javax.swing.JTable();
        txtFecEmi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNroRecibo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("RECIBOS POR HONORARIOS");
        setToolTipText(null);

        escritorio.setBackground(new java.awt.Color(255, 248, 239));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escritorio.setFocusCycleRoot(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        btnNuevo.setName("nuevo"); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar.setName("editar"); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminar.setName("eliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardar.setName("guardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        btnCancelar.setName("cancelar"); // NOI18N
        btnCancelar.setNextFocusableComponent(txtNroRecibo);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Nro. Recibo:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("RUC:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("Distrito:");

        jLabel7.setText("Apellidos:");

        txtRuc.setNextFocusableComponent(txtNom);
        txtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucKeyTyped(evt);
            }
        });

        txtApe.setNextFocusableComponent(cboDistrito);
        txtApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeFocusLost(evt);
            }
        });

        txtNom.setNextFocusableComponent(txtApe);
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomFocusLost(evt);
            }
        });

        jLabel8.setText("Concepto:");

        jLabel9.setText("Forma de pago:");

        jLabel10.setText("Importe Neto:");

        jLabel11.setText("Retención IR:");

        txtDirec.setNextFocusableComponent(cboPago);
        txtDirec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDirecFocusLost(evt);
            }
        });

        txtIR.setEditable(false);

        txtConcepto.setNextFocusableComponent(txtFecEmi);

        cboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Efectivo" }));
        cboPago.setNextFocusableComponent(txtImpNeto);

        cboDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Ancón",
            "Ate",
            "Barranco",
            "Breña",
            "Carabayllo",
            "Chaclacayo",
            "Chorrillos",
            "Cieneguilla",
            "Comas",
            "El Agustino",
            "Independencia",
            "Jesús María",
            "La Molina",
            "La Victoria",
            "Lima",
            "Lince",
            "Los Olivos",
            "Lurigancho",
            "Lurin",
            "Magdalena del Mar",
            "Miraflores",
            "Pachacamac",
            "Pucusana",
            "Pueblo Libre",
            "Puente Piedra",
            "Punta Hermosa",
            "Punta Negra",
            "Rímac",
            "San Bartolo",
            "San Borja",
            "San Isidro",
            "San Juan de Lurigancho",
            "San Juan de Miraflores",
            "San Luis",
            "San Martín de Porres",
            "San Miguel",
            "Santa Anita",
            "Santa María del Mar",
            "Santa Rosa",
            "Santiago de Surco",
            "Surquillo",
            "Villa El Salvador",
            "Villa María del Triunfo"
        }));
        cboDistrito.setNextFocusableComponent(txtDirec);

        txtImpNeto.setNextFocusableComponent(txtConcepto);
        txtImpNeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImpNetoFocusLost(evt);
            }
        });
        txtImpNeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImpNetoKeyTyped(evt);
            }
        });

        jLabel12.setText("Importe Total:");

        txtImpTotal.setEditable(false);

        tblHonorarios.setBackground(new java.awt.Color(255, 255, 255));
        tblHonorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO. RECIBO", "RUC", "NOMBRES", "APELLIDOS", "DISTRITO", "DIRECCIÓN", "F. PAGO", "CONCEPTO", "IMP. NETO", "RETENCIÓN IR", "IMP. TOTAL", "FEC. EMISIÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHonorarios.setFocusable(false);
        tblHonorarios.setRowHeight(25);
        tblHonorarios.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblHonorarios.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblHonorarios.setShowGrid(true);
        jScrollPane1.setViewportView(tblHonorarios);
        if (tblHonorarios.getColumnModel().getColumnCount() > 0) {
            tblHonorarios.getColumnModel().getColumn(0).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(1).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(2).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(2).setPreferredWidth(90);
            tblHonorarios.getColumnModel().getColumn(3).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(3).setPreferredWidth(125);
            tblHonorarios.getColumnModel().getColumn(4).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(4).setPreferredWidth(160);
            tblHonorarios.getColumnModel().getColumn(5).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(5).setPreferredWidth(170);
            tblHonorarios.getColumnModel().getColumn(6).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblHonorarios.getColumnModel().getColumn(7).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(7).setPreferredWidth(105);
            tblHonorarios.getColumnModel().getColumn(8).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(8).setPreferredWidth(200);
            tblHonorarios.getColumnModel().getColumn(9).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(9).setPreferredWidth(60);
            tblHonorarios.getColumnModel().getColumn(10).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(10).setPreferredWidth(60);
            tblHonorarios.getColumnModel().getColumn(11).setResizable(false);
            tblHonorarios.getColumnModel().getColumn(11).setPreferredWidth(60);
            tblHonorarios.getColumnModel().getColumn(12).setResizable(false);
        }

        txtFecEmi.setNextFocusableComponent(btnGuardar);
        txtFecEmi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFecEmiKeyTyped(evt);
            }
        });

        jLabel13.setText("Fec. Emisión:");

        txtNroRecibo.setActionCommand("<Not Set>");
        txtNroRecibo.setFocusCycleRoot(true);
        txtNroRecibo.setNextFocusableComponent(txtRuc);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIR, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecEmi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(98, 98, 98))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImpNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(19, 19, 19))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtNroRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtImpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtFecEmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtImpNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OcultarColumna(JTable tabla, int indiceColumna) {
        // Obtener la columna que se desea ocultar
        TableColumn col = tabla.getColumnModel().getColumn(indiceColumna);
        // Obtener el modelo de columna de la tabla
        TableColumnModel tcm = tabla.getColumnModel();
        // Remover la columna del modelo de columna
        tcm.removeColumn(col);
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        tblHonorarios.clearSelection();
        tblHonorarios.setRowSelectionAllowed(false);
        DatosRecibosHonorarios.Habilitar(escritorio, true);
        String codigo = DatosRecibosHonorarios.GenerarCodigo("reciboshonorarios", "RE", 7);
        txtId.setText(codigo);
        txtId.setEnabled(false);
        txtNroRecibo.requestFocus();
        esNuevo = true; // Indicamos que sera un nuevo registro
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Agrupar las cajas de texto
        JTextField[] camposTexto = {txtId, txtNroRecibo, txtRuc, txtNom, txtApe,
            txtDirec, txtConcepto, txtImpNeto, txtIR, txtImpTotal, txtFecEmi};

        DatosRecibosHonorarios.Editar(escritorio, tblHonorarios, camposTexto, cboDistrito, cboPago);
        esNuevo = false; // Indicamos que no sera un nuevo registro
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DatosRecibosHonorarios.Eliminar(tblHonorarios);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Seleccionamos todas las cajas
        JTextField[] campos = {txtNroRecibo, txtRuc, txtNom, txtApe, txtDirec, txtImpNeto, txtConcepto, txtFecEmi};

        // Validamos que todos los campos estén llenos
        if (!DatosRecibosHonorarios.Validar(campos)) {
            return;
        }

        // Validamos que se haya seleccionado un distrito y una forma de pago
        JComboBox[] combos = {cboDistrito, cboPago};
        for (JComboBox combo : combos) {
            if (combo.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(
                        null, "Debe escoger un distrito y una forma de pago.", "Advertencia", JOptionPane.WARNING_MESSAGE
                );
                combo.requestFocus();
                return;
            }
        }

        // Obtenemos el distrito y la forma de pago
        String distrito = cboDistrito.getSelectedItem().toString();
        String pago = cboPago.getSelectedItem().toString();

        // Creamos un objeto ReciboHonorario y le asignamos los valores de los campos
        ReciboHonorario recibo = new ReciboHonorario();
        recibo.setId(txtId.getText());
        recibo.setNroRecibo(txtNroRecibo.getText());
        recibo.setRuc(txtRuc.getText());
        recibo.setNombres(txtNom.getText());
        recibo.setApellidos(txtApe.getText());
        recibo.setDistrito(distrito);
        recibo.setDireccion(txtDirec.getText());
        recibo.setFormaPago(pago);
        recibo.setConcepto(txtConcepto.getText());
        recibo.setImporteNeto(Float.parseFloat(txtImpNeto.getText()));
        recibo.setRetencionIr(Float.parseFloat(txtIR.getText()));
        recibo.setImporteTotal(Float.parseFloat(txtImpTotal.getText()));
        recibo.setFecha(txtFecEmi.getText());

        // Insertamos o actualizamos el recibo en la base de datos
        if (esNuevo) {
            DatosRecibosHonorarios.Insertar(recibo, tblHonorarios);
        } else {
            DatosRecibosHonorarios.Actualizar(recibo, tblHonorarios);
        }

        // Limpiamos y deshabilitamos los campos del formulario
        DatosRecibosHonorarios.Limpiar(escritorio);
        DatosRecibosHonorarios.Habilitar(escritorio, false);
        tblHonorarios.clearSelection();
        tblHonorarios.setRowSelectionAllowed(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        DatosRecibosHonorarios.Limpiar(escritorio);
        DatosRecibosHonorarios.Habilitar(escritorio, false);
        tblHonorarios.clearSelection();
        tblHonorarios.setRowSelectionAllowed(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtImpNetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpNetoFocusLost
        String impuestoNeto = txtImpNeto.getText();
        if (!impuestoNeto.isEmpty()) {
            float impNeto = Float.parseFloat(impuestoNeto);
            float ir = Math.round(impNeto * 0.08f * 100.0) / 100.0f;
            float impTotal = Math.round((impNeto - ir) * 100.0) / 100.0f;

            txtIR.setText(String.valueOf(ir));
            txtImpTotal.setText(String.valueOf(impTotal));
        }
    }//GEN-LAST:event_txtImpNetoFocusLost

    private void txtFecEmiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFecEmiKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_BACK_SPACE) {
            // permitir eliminar el carácter anterior incluso si es una diagonal
            String fecha = txtFecEmi.getText();
            if (!fecha.isEmpty()) {
                // eliminar el último carácter de la cadena
                fecha = fecha.substring(0, fecha.length() - 1);
                txtFecEmi.setText(fecha);
            }
        } else if (!Character.isDigit(c)) {
            evt.consume(); // Si no es un número, se ignora el evento de tecla
        }

        String fecha = txtFecEmi.getText();
        int length = fecha.length();
        if (length == 2 || length == 5) { // Si se ha ingresado un día o un mes completo, se agrega el guión correspondiente
            fecha += "/";
            txtFecEmi.setText(fecha);
        }

        if (length >= 10) {
            evt.consume(); // Si ya se ha ingresado la fecha completa, se ignora el evento de tecla
        }
    }//GEN-LAST:event_txtFecEmiKeyTyped

    private void txtRucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == evt.VK_BACK_SPACE) || (c == evt.VK_DELETE))) {
            evt.consume();// Si no es un número, se ignora el evento de tecla
        }
        if (txtRuc.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRucKeyTyped

    private void txtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusLost
        String text = txtNom.getText().trim();
        txtNom.setText(text);
    }//GEN-LAST:event_txtNomFocusLost

    private void txtApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeFocusLost
        String text = txtApe.getText().trim();
        txtApe.setText(text);
    }//GEN-LAST:event_txtApeFocusLost

    private void txtDirecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDirecFocusLost
        String text = txtDirec.getText().trim();
        txtDirec.setText(text);
    }//GEN-LAST:event_txtDirecFocusLost

    private void txtImpNetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpNetoKeyTyped
        char c = evt.getKeyChar();
        String text = txtImpNeto.getText();

        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume(); // Si no es un número o un punto, se ignora el evento de tecla
        } else if (c == '.' && text.contains(".")) {
            evt.consume(); // Si el carácter ingresado es un punto y ya hay un punto en el campo de texto, se ignora el evento de tecla
        } else if (text.contains(".") && text.length() - text.indexOf(".") > 2) {
            evt.consume(); // Si ya hay dos decimales en el campo de texto, se ignora el evento de tecla
        } else if (text.equals("0") && c != '.') {
            evt.consume(); // Si el primer carácter es 0 y el siguiente carácter no es un punto, se ignora el evento de tecla
        }
    }//GEN-LAST:event_txtImpNetoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboPago;
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHonorarios;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtFecEmi;
    private javax.swing.JTextField txtIR;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImpNeto;
    private javax.swing.JTextField txtImpTotal;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNroRecibo;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
