/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_gm.Asistencias;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jeanv
 */
public class frmAsistencias extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAsistencias
     */
    public frmAsistencias() {
        initComponents();
        // Personalizar header
        JTableHeader header = tblAsistencias.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(JLabel.CENTER);
                setBackground(Color.DARK_GRAY);
                setForeground(Color.WHITE);
                setFont(getFont().deriveFont(Font.BOLD, 13));
                return this;
            }
        });

        // Cargar empleados
        DatosAsistencia.CargarEmpleados(cboEmpleado);

        RowsRenderer renderer = new RowsRenderer(0);
        tblAsistencias.setDefaultRenderer(Object.class, renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsistencias = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        cboPeriodo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("ASISTENCIAS");

        jPanel1.setBackground(new java.awt.Color(255, 248, 239));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDni.setText("jLabel2");
        lblDni.setHorizontalAlignment(JLabel.CENTER);

        tblAsistencias.setBackground(new java.awt.Color(255, 255, 255));
        tblAsistencias.setForeground(new java.awt.Color(0, 0, 0));
        tblAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DÍA", "FECHA", "ENTRADA", "SALIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAsistencias.setFocusable(false);
        tblAsistencias.setRowHeight(25);
        tblAsistencias.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblAsistencias.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblAsistencias.setShowGrid(true);
        tblAsistencias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAsistencias);
        if (tblAsistencias.getColumnModel().getColumnCount() > 0) {
            tblAsistencias.getColumnModel().getColumn(0).setResizable(false);
            tblAsistencias.getColumnModel().getColumn(1).setResizable(false);
            tblAsistencias.getColumnModel().getColumn(2).setResizable(false);
            tblAsistencias.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setText("Periodo:");

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmpleado.setText("jLabel1");
        lblEmpleado.setHorizontalAlignment(JLabel.CENTER);

        cboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "102022", "112022" }));
        cboPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPeriodoActionPerformed(evt);
            }
        });

        jLabel3.setText("Empleado:");

        cboEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String ultimoPeriodoSeleccionado = "";
    private String ultimoEmpleadoSeleccionado = "";

    private void actualizarEmpleadoSeleccionado() {
        // Mostrar el empleado seleccionado
        lblEmpleado.setText(cboEmpleado.getSelectedItem().toString());

        // Mostrar el DNI del empleado seleccionado
        lblDni.setText(DatosAsistencia.ObtenerDNI(cboEmpleado));
    }

    private void cboEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmpleadoActionPerformed
        String empleadoSeleccionado = cboEmpleado.getSelectedItem().toString();
        String periodoSeleccionado = cboPeriodo.getSelectedItem().toString();

        if (!empleadoSeleccionado.equals(ultimoEmpleadoSeleccionado) || !periodoSeleccionado.equals(ultimoPeriodoSeleccionado)) {
            actualizarEmpleadoSeleccionado();

            String periodo = periodoSeleccionado;
            DatosAsistencia.fillTableForPeriod(tblAsistencias, periodo, cboEmpleado);

            ultimoEmpleadoSeleccionado = empleadoSeleccionado;
            ultimoPeriodoSeleccionado = periodoSeleccionado;
        }
    }//GEN-LAST:event_cboEmpleadoActionPerformed

    private void cboPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPeriodoActionPerformed
    String periodoSeleccionado = cboPeriodo.getSelectedItem().toString();
    String empleadoSeleccionado = cboEmpleado.getSelectedItem().toString();
    
    if (!periodoSeleccionado.equals(ultimoPeriodoSeleccionado) || !empleadoSeleccionado.equals(ultimoEmpleadoSeleccionado)) {
        actualizarEmpleadoSeleccionado();
        
        String periodo = periodoSeleccionado;
        DatosAsistencia.fillTableForPeriod(tblAsistencias, periodo, cboEmpleado);
        
        ultimoPeriodoSeleccionado = periodoSeleccionado;
        ultimoEmpleadoSeleccionado = empleadoSeleccionado;
    }
    }//GEN-LAST:event_cboPeriodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEmpleado;
    private javax.swing.JComboBox<String> cboPeriodo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JTable tblAsistencias;
    // End of variables declaration//GEN-END:variables
}
