/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_gm.Comunicacion;

import java.io.Console;
import java.sql.Date;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto_gm.proyectos.DatosProyectos;
import proyecto_gm.proyectos.Proyectos;
/**
 *
 * @author pc_sistemas2022
 */
public class frmComunicacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmComunicacion
     */
    Comunicacion entidad;
    Utilitario.EstadoProceso estado;
    public frmComunicacion(JDesktopPane contenedorPadre, Utilitario.EstadoProceso estado,Comunicacion entidadComunicacion) {
        initComponents();
        contenedorPadre.add(this);
        entidad = entidadComunicacion;
        this.estado = estado;
        
    }
    public frmComunicacion(JDesktopPane contenedorPadre, Utilitario.EstadoProceso estado){
        initComponents();
        contenedorPadre.add(this);
        this.estado = estado;
        
    }
    public frmComunicacion(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeshacer = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboTipoComunicacion = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdPeriodo = new javax.swing.JTextField();
        cboNomProyecto = new javax.swing.JComboBox<>();
        cboFlujo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCodDocRespuesta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAsunto = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtEnlace = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("MANTENIMIENTO DE COMUNICACION");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(104, 60));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeshacer);
        btnDeshacer.setBounds(180, 10, 53, 30);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(130, 10, 53, 30);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(70, 6, 53, 30);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(38, 6, 53, 30);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(6, 6, 53, 30);

        jLabel8.setText("Flujo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(620, 70, 23, 14);

        jLabel1.setText("Periodo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 40, 36, 14);

        jLabel4.setText("dd/mm/yyyy");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 70, 70, 14);

        jLabel2.setText("Proyecto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 45, 43, 14);

        cboTipoComunicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carta", "Correo", "Llamada" }));
        getContentPane().add(cboTipoComunicacion);
        cboTipoComunicacion.setBounds(520, 70, 90, 20);

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFecha.setToolTipText("Ingresar con el formato dd/mm/YYYY");
        getContentPane().add(txtFecha);
        txtFecha.setBounds(270, 70, 110, 20);

        jLabel11.setText("Fecha");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 70, 29, 14);
        getContentPane().add(txtIdPeriodo);
        txtIdPeriodo.setBounds(650, 40, 111, 20);

        cboNomProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Via Expresa Santa Rosa", "PEC", "Proyecto Llata" }));
        cboNomProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNomProyectoItemStateChanged(evt);
            }
        });
        cboNomProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(cboNomProyecto);
        cboNomProyecto.setBounds(71, 42, 490, 20);

        cboFlujo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emision", "Recepcion" }));
        getContentPane().add(cboFlujo);
        cboFlujo.setBounds(660, 70, 100, 20);

        jLabel3.setText("Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(18, 73, 10, 14);
        getContentPane().add(txtId);
        txtId.setBounds(71, 70, 140, 20);

        jLabel5.setText("Cod.Doc.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 101, 45, 14);

        txtCodDoc.setText("VESR-EXT-GEN-ITF-001");
        getContentPane().add(txtCodDoc);
        txtCodDoc.setBounds(67, 98, 239, 20);

        jLabel10.setText("Doc.Respuesta");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(324, 101, 73, 14);
        getContentPane().add(txtCodDocRespuesta);
        txtCodDocRespuesta.setBounds(407, 98, 350, 20);

        jLabel6.setText("Origen");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 129, 32, 14);

        txtOrigen.setText("CONSORCIO SANTA ROSA");
        getContentPane().add(txtOrigen);
        txtOrigen.setBounds(66, 126, 690, 20);

        jLabel7.setText("Destino");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 157, 36, 14);

        txtDestino.setText("SEDAPAL");
        getContentPane().add(txtDestino);
        txtDestino.setBounds(66, 154, 690, 20);

        jLabel9.setText("Asunto");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 182, 34, 14);

        txtAsunto.setColumns(20);
        txtAsunto.setRows(5);
        txtAsunto.setText("REUBICACION Y VALIDACION DE INTERFERENCIA");
        jScrollPane1.setViewportView(txtAsunto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(64, 182, 690, 113);

        jLabel12.setText("Estado");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 277, 33, 14);

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proceso", "Resuelto", "Archivado" }));
        getContentPane().add(cboEstado);
        cboEstado.setBounds(61, 274, 125, 20);

        jLabel13.setText("Enlace");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(192, 277, 31, 14);

        txtEnlace.setText("SERVIDOR/CARTAS/SEDAPAL/0001");
        getContentPane().add(txtEnlace);
        txtEnlace.setBounds(232, 274, 520, 20);

        jLabel14.setText("Tipo");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(490, 70, 20, 14);

        setBounds(0, 0, 789, 344);
    }// </editor-fold>//GEN-END:initComponents
    enum TipoMensaje{
        INFORMACION,
        ALERTA,
        ERROR,
        PREGUNTA
    }
    
    private void Limpiar(){
        this.cboNomProyecto.setSelectedIndex(-1);
        this.txtIdPeriodo.setText("");
        this.txtFecha.setText("");
        this.cboTipoComunicacion.setSelectedIndex(-1);
        this.cboFlujo.setSelectedIndex(-1);
        this.txtCodDoc.setText("");
        this.txtCodDocRespuesta.setText("");
        this.txtOrigen.setText("");
        this.txtDestino.setText("");
        this.txtAsunto.setText("");
        this.cboEstado.setSelectedIndex(-1);
        this.txtEnlace.setText("");
        this.txtId.setText("");
    }
    
    private void HabilitarControles(boolean estado){
        this.cboNomProyecto.setEnabled(estado);
        this.txtIdPeriodo.setEnabled(estado);
        
        this.txtId.setEnabled(estado);
        this.txtFecha.setEnabled(estado);
        this.cboTipoComunicacion.setEnabled(estado);
        this.cboFlujo.setEnabled(estado);
                
        this.txtCodDoc.setEnabled(estado);
        this.txtCodDocRespuesta.setEnabled(estado);
        this.txtOrigen.setEnabled(estado);
        this.txtDestino.setEnabled(estado);
        this.txtAsunto.setEnabled(estado);
        
        this.cboEstado.setEnabled(estado);
        this.txtEnlace.setEnabled(estado);
    }
    
    private void LeerDatos(){
        this.cboNomProyecto.setSelectedIndex(1);
        txtIdPeriodo.setText(entidad.getIdPeriodo());
        txtFecha.setText(entidad.getFecha().toString());
        cboTipoComunicacion.setSelectedIndex(1);
        cboFlujo.setSelectedIndex(1);
        txtCodDoc.setText(entidad.getCodDoc());
        txtCodDocRespuesta.setText(entidad.getCodDocRespuesta());
        txtOrigen.setText(entidad.getOrigen());
        txtDestino.setText(entidad.getDestino());
        txtAsunto.setText(entidad.getAsunto());
        cboEstado.setSelectedIndex(1);
        txtEnlace.setText(entidad.getEnlace());
        
    }
private void MostrarMensaje(String contenido, TipoMensaje tipo ){
    
    if( null != tipo)switch (tipo) {
            case INFORMACION:
                JOptionPane.showMessageDialog(this, contenido, "SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                break;
            case ERROR:
                JOptionPane.showMessageDialog(this, contenido, "SISTEMA", JOptionPane.ERROR_MESSAGE);
                break;
            case PREGUNTA:
                JOptionPane.showConfirmDialog(this, contenido, "SISTEMA",JOptionPane.YES_NO_OPTION);
                break;
            default:
                break;
        }
    
}
    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        // TODO add your handling code here:
        Limpiar();
        HabilitarBotones(true);
        HabilitarControles(false);
        estado = Utilitario.EstadoProceso.CONSULTAR;
        
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:z
        System.out.println(cboNomProyecto.getSelectedItem());
        Proyectos p = (Proyectos)cboNomProyecto.getSelectedItem();
        System.out.println(p.getId()); 
        
        /*
        boolean procesoExitoso = false;
        entidad = new Comunicacion();
        if(cboNomProyecto.getSelectedIndex() == -1){
             Utilitario.MostrarMensaje("Seleccionar nombre de proyecto", Utilitario.TipoMensaje.error);
             return;
        }
        
        
        // anio - mes- dia
        // 10/12/2022
        //valdiar la fecha sea dd/mm/YYYY
        String anio = txtFecha.getText().substring(6, 10);
        String mes = txtFecha.getText().substring(3, 5);
        String dia = txtFecha.getText().substring(0, 2);
        String fechaFormateada = anio+"-"+mes+"-"+dia;
        
        entidad.setId(txtId.getText());
        entidad.setIdPeriodo(txtIdPeriodo.getText());
        entidad.setNombreProyecto(cboNomProyecto.getSelectedItem().toString());
        //tipo de comunicacion
        entidad.setTipo(cboTipoComunicacion.getSelectedIndex());  
        //codigo documento
        entidad.setCodDoc(txtCodDoc.getText());
        //origen
        entidad.setOrigen(txtOrigen.getText());
        //destino
        entidad.setDestino(txtDestino.getText());
        //flujo
        entidad.setFlujo(cboFlujo.getSelectedIndex());
        //asunto
        entidad.setAsunto(txtAsunto.getText());
        //fecha        
        entidad.setFecha(Date.valueOf(fechaFormateada));                        
        //documento respuesta
        entidad.setCodDocRespuesta(txtCodDocRespuesta.getText());                
        //estado
        entidad.setEstado(cboEstado.getSelectedIndex());
        //enlace
        entidad.setEnlace(txtEnlace.getText());
        if(estado == Utilitario.EstadoProceso.NUEVO){
            procesoExitoso  = DatosComunicacion.Insertar(entidad);                
            
        }else if(estado == Utilitario.EstadoProceso.EDITAR){
            procesoExitoso = DatosComunicacion.Actualizar(entidad);
                        
            
        }
        if(procesoExitoso == true){
            //limpiar
            Limpiar();
            HabilitarBotones(true);
            HabilitarControles(false);
        }
*/

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if(txtId.getText().equals("")){
            Utilitario.MostrarMensaje("Debe tener un valor en id para editar", Utilitario.TipoMensaje.alerta);
            return;
        }
        estado = Utilitario.EstadoProceso.EDITAR;
        HabilitarBotones(true);
        HabilitarControles(true);
        txtId.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed
          List<Proyectos> lista =  DatosProyectos.listar();
          String[] codigos = new String[lista.size()];
    private void Iniciarvalores(){
      //iniciar variables por defecto
         String sFecha = Utilitario.TraerFechaActual();
         txtFecha.setText(sFecha);
         
         //asignar periodo por defecto
         String mes = txtFecha.getText().substring(3, 5);
         String anio = txtFecha.getText().substring(6, 10);
         txtIdPeriodo.setText(mes+anio);
         
         //asingar codigo a la caja de t4exto codigo
         String idGenerado = DatosComunicacion.GenerarCodigo();
         txtId.setText(idGenerado);
         
           this.cboNomProyecto.removeAllItems();
           int x = 0;
           for (Proyectos elemento : lista) {
               
                //modeloCombo.addElement(elemento);
                codigos[x] = elemento.getId();
                this.cboNomProyecto.addItem(elemento.getDescripcion());
                x++;
          }
           
        
}
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
//        desbloquear();btnGuardar.setEnabled(true);btnDeshacer.setEnabled(true);
        estado = Utilitario.EstadoProceso.NUEVO;
        HabilitarBotones(false);
        HabilitarControles(true);
        Limpiar();
       Iniciarvalores();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void HabilitarBotones(boolean estado){
     btnAgregar.setEnabled(estado);
     btnEditar.setEnabled(estado);
     btnEliminar.setEnabled(estado);
     btnGuardar.setEnabled(!estado);
     btnDeshacer.setEnabled(!estado);
}
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
     //JOptionPane.showMessageDialog(this, entidad.getNombreProyecto());
     
     if(estado == Utilitario.EstadoProceso.NUEVO){
         HabilitarBotones(false);
         HabilitarControles(true);
         Limpiar();
         Iniciarvalores();
         
     }else if(estado == Utilitario.EstadoProceso.EDITAR){
         HabilitarBotones(false);
        if(entidad != null) {
            LeerDatos();
        }
        HabilitarControles(false);
     }
     
     
    }//GEN-LAST:event_formInternalFrameOpened

    private void cboNomProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomProyectoActionPerformed
     
    }//GEN-LAST:event_cboNomProyectoActionPerformed

    private void cboNomProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNomProyectoItemStateChanged
           try{
        //Proyectos p = (Proyectos)this.cboNomProyecto.getSelectedItem();
        //System.out.println(p.getId()+ "-"+ p.getDescripcion()); 
         int indiceSeleccionado = cboNomProyecto.getSelectedIndex();
         String codigoSeleccionado = "", valorSeleccionado = "";
         codigoSeleccionado = codigos[indiceSeleccionado];
         valorSeleccionado = this.cboNomProyecto.getSelectedItem().toString();
         System.out.println(codigoSeleccionado+ "-"+ valorSeleccionado); 
        //Proyectos p = (Proyectos)cboNomProyecto.getSelectedItem();
        
        
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_cboNomProyectoItemStateChanged
/*
    -- formateo de fecha java 
         
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
        LocalDateTime fechaActual = LocalDateTime.now();
        String sFecha = fechaActual.format(dtf);
        
        txtFecha.setText(sFecha);
        //configurar columnas de grilla
        DefaultTableModel modeloComunicacion = (DefaultTableModel)jTable1.getModel();
        datos.ConfigurarGrilla(modeloComunicacion);
        
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboFlujo;
    private javax.swing.JComboBox<String> cboNomProyecto;
    private javax.swing.JComboBox<String> cboTipoComunicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAsunto;
    private javax.swing.JTextField txtCodDoc;
    private javax.swing.JTextField txtCodDocRespuesta;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtEnlace;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPeriodo;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
