/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_gm.Comunicacion;

import com.mysql.cj.jdbc.CallableStatement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import proyecto_gm.Comunicacion.*;
import javax.swing.table.TableModel;
import static proyecto_gm.Comunicacion.DatosComunicacion.Actualizar;
import proyecto_gm.ConexionBD;
import proyecto_gm.Facultades.DatosFacultades;

/**
 *
 * @author pc_sistemas2022
 *
 */
public class frmListaComunicacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaComunicacion
     */
    TableRowSorter<TableModel> rowSorter;
    JDesktopPane panelPadre;

    public void AsignarPadre(JDesktopPane padre) {
        this.panelPadre = padre;
    }

    public frmListaComunicacion() {
        initComponents();

        JTableHeader header = tblDatos.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(JLabel.CENTER);
                setBackground(Color.DARK_GRAY);
                setForeground(Color.WHITE);
                setFont(getFont().deriveFont(Font.BOLD, 13));
                return this;
            }
        });
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        DatosComunicacion.Listar(modelo);
        System.out.println("Total filas: " + modelo.getRowCount());
        tblDatos.setRowHeight(25);
        tblDatos.repaint();
        tblDatos.revalidate();

        HabilitarBotones(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtOrigenFiltro = new javax.swing.JTextField();
        txtDestinoFiltro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboFlujo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFechaInicialFiltro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaFinalFiltro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        rbVerTodo = new javax.swing.JRadioButton();
        rbVerFiltrado = new javax.swing.JRadioButton();

        setClosable(true);
        setForeground(java.awt.Color.lightGray);
        setIconifiable(true);
        setResizable(true);
        setTitle("COMUNICACIONES");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Periodo", "Proyecto", "Tipo", "Cod.Doc", "Origen", "Destino", "Flujo", "Asunto", "Fecha", "Cod.Doc.Resp", "estado", "Enlace"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setFocusable(false);
        tblDatos.setShowGrid(true);
        jScrollPane1.setViewportView(tblDatos);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Origen");

        txtOrigenFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrigenFiltroKeyTyped(evt);
            }
        });

        txtDestinoFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestinoFiltroKeyTyped(evt);
            }
        });

        jLabel2.setText("Destino");

        jLabel3.setText("Flujo");

        cboFlujo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emision", "Recepcion" }));

        jLabel4.setText("Estado");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proceso", "Resuelto", "Archivado" }));

        jLabel6.setText("Fecha inicial");

        txtFechaInicialFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaInicialFiltroKeyTyped(evt);
            }
        });

        jLabel7.setText("Fecha Final");

        txtFechaFinalFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaFinalFiltroKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVerTodo);
        rbVerTodo.setText("Ver registros");
        rbVerTodo.setName("opciones"); // NOI18N
        rbVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerTodoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVerFiltrado);
        rbVerFiltrado.setText("Ver registros filtrado");
        rbVerFiltrado.setName("opciones"); // NOI18N
        rbVerFiltrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerFiltradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbVerTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbVerFiltrado)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrigenFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(txtDestinoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFlujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicialFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaFinalFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtOrigenFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbVerFiltrado)
                        .addComponent(rbVerTodo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaFinalFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestinoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(cboFlujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtFechaInicialFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void HabilitarBotones(boolean estado) {
        btnAgregar.setEnabled(estado);
        btnEditar.setEnabled(estado);
        btnEliminar.setEnabled(estado);

    }

    private String LeerCeldaActual(int columnaActual) {

        return tblDatos.getValueAt(tblDatos.getSelectedRow(), columnaActual).toString();
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Crear el formulario de comunicación
        frmComunicacion frm = new frmComunicacion(panelPadre, Utilitario.EstadoProceso.NUEVO);

        // Generar el código con tu método
        String nuevoCodigo = DatosComunicacion.GenerarCodigo();

        // Establecer el código en el formulario
        frm.setCodigoGenerado(nuevoCodigo);

        // Mostrar el formulario
        frm.setVisible(true);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
            return;
        }

        try {
            // Obtener datos de la fila
            String id = tblDatos.getValueAt(fila, 0).toString();
            String periodo = tblDatos.getValueAt(fila, 1).toString();
            String proyecto = tblDatos.getValueAt(fila, 2).toString();
            String tipo = tblDatos.getValueAt(fila, 3).toString();
            String codDoc = tblDatos.getValueAt(fila, 4).toString();
            String origen = tblDatos.getValueAt(fila, 5).toString();
            String destino = tblDatos.getValueAt(fila, 6).toString();
            String flujo = tblDatos.getValueAt(fila, 7).toString();
            String asunto = tblDatos.getValueAt(fila, 8).toString();
            String fecha = tblDatos.getValueAt(fila, 9).toString();
            String codDocResp = tblDatos.getValueAt(fila, 10).toString();
            String estado = tblDatos.getValueAt(fila, 11).toString();
            String enlace = tblDatos.getValueAt(fila, 12).toString();

            // Debug: Mostrar datos obtenidos
            System.out.println("Datos obtenidos para edición:");
            System.out.println("ID: " + id);
            System.out.println("Proyecto: " + proyecto);
            System.out.println("Tipo: " + tipo);
            System.out.println("Flujo: " + flujo);
            System.out.println("Estado: " + estado);

            // Crear formulario en modo EDITAR
            frmComunicacion frm = new frmComunicacion(panelPadre, Utilitario.EstadoProceso.EDITAR);
            //frm.setEsEdicion(true);
            frm.setVisible(true);
            frm.setDatos(id, periodo, proyecto, tipo, codDoc, origen, destino,
                    flujo, asunto, fecha, codDocResp, estado, enlace);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblDatos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el registro?");
            if (confirmar == JOptionPane.OK_OPTION) {
                int id = Integer.parseInt(tblDatos.getValueAt(fila, 0).toString());
                Comunicacion c = new Comunicacion();
                c.setId(String.valueOf(id));

                boolean resultado = DatosComunicacion.Eliminar(c);

                if (resultado) {
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                    DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
                    modelo.removeRow(fila);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtOrigenFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigenFiltroKeyTyped
    }//GEN-LAST:event_txtOrigenFiltroKeyTyped

    private void txtDestinoFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoFiltroKeyTyped
    }//GEN-LAST:event_txtDestinoFiltroKeyTyped

    private void txtFechaInicialFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicialFiltroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicialFiltroKeyTyped

    private void txtFechaFinalFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaFinalFiltroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinalFiltroKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String origen = txtOrigenFiltro.getText().trim();
        String destino = txtDestinoFiltro.getText().trim();
        String flujo = cboFlujo.getSelectedItem() != null ? cboFlujo.getSelectedItem().toString() : "";
        String estado = cboEstado.getSelectedItem() != null ? cboEstado.getSelectedItem().toString() : "";
        String fechaInicial = txtFechaInicialFiltro.getText().trim();
        String fechaFinal = txtFechaFinalFiltro.getText().trim();

        // Validar formato de fecha
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date fechaIniSQL = null;
        java.sql.Date fechaFinSQL = null;

        try {
            if (!fechaInicial.isEmpty()) {
                java.util.Date fechaIniUtil = sdf.parse(fechaInicial);
                fechaIniSQL = new java.sql.Date(fechaIniUtil.getTime());
            }

            if (!fechaFinal.isEmpty()) {
                java.util.Date fechaFinUtil = sdf.parse(fechaFinal);
                fechaFinSQL = new java.sql.Date(fechaFinUtil.getTime());
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de fecha inválido. Use yyyy-MM-dd.");
            return;
        }

        // Limpiar tabla
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        modelo.setRowCount(0);

        // Llamar al método Buscar de DatosComunicacion
        DatosComunicacion.Buscar(modelo, origen, destino, flujo, estado, fechaIniSQL, fechaFinSQL);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbVerFiltradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerFiltradoActionPerformed
        HabilitarFiltros(true);
    }//GEN-LAST:event_rbVerFiltradoActionPerformed

    private void rbVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerTodoActionPerformed
        HabilitarFiltros(false);      // Desactiva todos los filtros de búsqueda
        RefrescarTabla();             // Muestra todos los registros
        //
    }//GEN-LAST:event_rbVerTodoActionPerformed
   
    private void HabilitarFiltros(boolean habilitar) {
        txtOrigenFiltro.setEnabled(habilitar);
        txtDestinoFiltro.setEnabled(habilitar);
        cboFlujo.setEnabled(habilitar);
        cboEstado.setEnabled(habilitar);
        txtFechaInicialFiltro.setEnabled(habilitar);
        txtFechaFinalFiltro.setEnabled(habilitar);
        btnBuscar.setEnabled(habilitar);
    }

    public void RefrescarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        modelo.setRowCount(0);
        DatosComunicacion.Listar(modelo);
    }
    // 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboFlujo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbVerFiltrado;
    private javax.swing.JRadioButton rbVerTodo;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDestinoFiltro;
    private javax.swing.JTextField txtFechaFinalFiltro;
    private javax.swing.JTextField txtFechaInicialFiltro;
    private javax.swing.JTextField txtOrigenFiltro;
    // End of variables declaration//GEN-END:variables
}
